"""
QueryState: Typed state machine for multi-agent pipeline.

This module defines the complete state structure passed between agents,
ensuring type safety and reproducibility across the agent orchestration loop.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple
from datetime import datetime
from enum import Enum


class AgentType(str, Enum):
    """Enumeration of agent types in the pipeline."""
    INTENT_PARSER = "intent_parser"
    ONTOLOGY_MAPPER = "ontology_mapper"
    CONSTRAINT_VALIDATOR = "constraint_validator"
    EXECUTION_PLANNER = "execution_planner"
    RESULT_VERIFIER = "result_verifier"


class ConstraintType(str, Enum):
    """Types of business constraints."""
    TAX_EXCLUSION = "tax_exclusion"
    REGION_FILTER = "region_filter"
    DATE_RANGE = "date_range"
    ENTITY_MEMBERSHIP = "entity_membership"
    METRIC_BOUNDS = "metric_bounds"
    JOIN_CARDINALITY = "join_cardinality"
    DATA_GOVERNANCE = "data_governance"


@dataclass
class ExtractedIntent:
    """Natural language intent extracted by IntentParserAgent."""
    entities: List[str] = field(default_factory=list)
    metrics: List[str] = field(default_factory=list)
    filters: Dict[str, Any] = field(default_factory=dict)
    temporal_spec: Optional[Dict[str, Any]] = None
    confidence_scores: Dict[str, float] = field(default_factory=dict)
    raw_text: str = ""

    @property
    def extraction_confidence(self) -> float:
        """Aggregate confidence score for the extracted intent."""
        if not self.confidence_scores:
            return 0.0
        return sum(self.confidence_scores.values()) / len(self.confidence_scores)


@dataclass
class OntologyMapping:
    """Binding of intent elements to ontology paths."""
    entity_name: str
    ontology_path: str
    similarity_score: float  # 0-1 semantic similarity
    aliases_matched: List[str] = field(default_factory=list)
    is_valid: bool = True
    resolution_method: str = ""  # "exact", "semantic", "fuzzy"


@dataclass
class ValidatedConstraint:
    """Business rule after validation."""
    constraint_type: ConstraintType
    description: str
    is_satisfied: bool
    details: Dict[str, Any] = field(default_factory=dict)
    severity: str = "required"  # "required", "warning", "info"


@dataclass
class ExecutionPlan:
    """Query execution plan generated by ExecutionPlannerAgent."""
    sql_template: str
    parameters: Dict[str, Any] = field(default_factory=dict)
    join_order: List[str] = field(default_factory=list)
    estimated_rows: int = 0
    query_dag: Dict[str, List[str]] = field(default_factory=dict)
    optimization_notes: str = ""


@dataclass
class QueryResult:
    """Single result row from database query."""
    data: Dict[str, Any]
    confidence: float = 1.0
    anomaly_score: Optional[float] = None


@dataclass
class QueryResults:
    """Complete query results with metadata."""
    rows: List[QueryResult] = field(default_factory=list)
    row_count: int = 0
    columns: List[str] = field(default_factory=list)
    execution_time_ms: float = 0.0
    query_hash: str = ""
    plausibility_score: float = 1.0


@dataclass
class DriftScore:
    """Semantic drift metric at a specific iteration."""
    iteration: int
    intent_alignment: float  # 0-1
    constraint_adherence: float  # 0-1
    result_plausibility: float  # 0-1
    composite_drift: float  # 0-1
    timestamp: datetime = field(default_factory=datetime.utcnow)
    notes: str = ""


@dataclass
class ExecutionMetadata:
    """Metadata about query execution."""
    query_id: str
    user_id: Optional[str] = None
    database_name: str = ""
    execution_start: datetime = field(default_factory=datetime.utcnow)
    execution_end: Optional[datetime] = None
    total_iterations: int = 0
    converged: bool = False
    convergence_reason: str = ""  # "threshold", "max_iterations", "error"


@dataclass
class TraceRecord:
    """Single trace record for debugging and audit trail."""
    timestamp: datetime
    agent: AgentType
    action: str
    details: Dict[str, Any]
    state_snapshot: Optional[Dict[str, Any]] = None


@dataclass
class QueryState:
    """
    Complete typed state machine for query processing pipeline.
    
    Passed between agents, ensuring:
    - Type safety
    - Reproducibility
    - Full traceability
    - Constraint enforcement
    """
    # Input and basic tracking
    user_query: str
    query_id: str
    metadata: ExecutionMetadata
    
    # Intent extraction (Intent Parser → others)
    intent: Optional[ExtractedIntent] = None
    
    # Ontology grounding (Ontology Mapper → others)
    mappings: List[OntologyMapping] = field(default_factory=list)
    
    # Business rule validation (Constraint Validator → others)
    constraints: List[ValidatedConstraint] = field(default_factory=list)
    all_constraints_satisfied: bool = False
    
    # Query planning (Execution Planner → others)
    plan: Optional[ExecutionPlan] = None
    
    # Execution results (Result Verifier → others)
    results: Optional[QueryResults] = None
    
    # Semantic drift tracking
    drift_scores: List[DriftScore] = field(default_factory=list)
    final_drift: Optional[float] = None
    converged: bool = False
    
    # Execution trace
    trace_log: List[TraceRecord] = field(default_factory=list)
    
    # Error handling
    error: Optional[str] = None
    error_agent: Optional[AgentType] = None
    
    # Additional context
    context: Dict[str, Any] = field(default_factory=dict)
    
    def add_trace(
        self,
        agent: AgentType,
        action: str,
        details: Dict[str, Any],
        include_state_snapshot: bool = False
    ) -> None:
        """Log a trace record for this query."""
        state_snapshot = None
        if include_state_snapshot:
            state_snapshot = {
                "intent": self.intent.__dict__ if self.intent else None,
                "mappings_count": len(self.mappings),
                "constraints_count": len(self.constraints),
                "plan": self.plan.__dict__ if self.plan else None,
                "results_count": self.results.row_count if self.results else 0,
                "drift_scores_count": len(self.drift_scores),
            }
        
        record = TraceRecord(
            timestamp=datetime.utcnow(),
            agent=agent,
            action=action,
            details=details,
            state_snapshot=state_snapshot,
        )
        self.trace_log.append(record)
    
    def get_trace_summary(self) -> Dict[str, Any]:
        """Generate summary of execution trace."""
        return {
            "query_id": self.query_id,
            "total_iterations": self.metadata.total_iterations,
            "converged": self.converged,
            "final_drift": self.final_drift,
            "trace_records": len(self.trace_log),
            "execution_time_ms": (
                (self.metadata.execution_end - self.metadata.execution_start).total_seconds() * 1000
                if self.metadata.execution_end
                else None
            ),
            "constraints_satisfied": self.all_constraints_satisfied,
        }
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert state to dictionary for serialization."""
        return {
            "user_query": self.user_query,
            "query_id": self.query_id,
            "metadata": {
                "query_id": self.metadata.query_id,
                "database_name": self.metadata.database_name,
                "execution_start": self.metadata.execution_start.isoformat(),
                "execution_end": self.metadata.execution_end.isoformat() if self.metadata.execution_end else None,
                "total_iterations": self.metadata.total_iterations,
                "converged": self.metadata.converged,
            },
            "intent": self.intent.__dict__ if self.intent else None,
            "mappings_count": len(self.mappings),
            "constraints_satisfied": self.all_constraints_satisfied,
            "plan": self.plan.__dict__ if self.plan else None,
            "results_count": self.results.row_count if self.results else 0,
            "final_drift": self.final_drift,
            "converged": self.converged,
            "trace_records": len(self.trace_log),
            "trace_log": [
                {
                    "timestamp": record.timestamp.isoformat(),
                    "agent": record.agent.value,
                    "action": record.action,
                    "details": record.details,
                }
                for record in self.trace_log
            ],
            "error": self.error,
        }
